# Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]



# # Stage 1: Install dependencies
# FROM node:20-alpine AS deps
# WORKDIR /app

# COPY package.json package-lock.json* ./
# RUN npm ci

# # Stage 2: Build the application
# FROM node:20-alpine AS builder
# WORKDIR /app

# COPY --from=deps /app/node_modules ./node_modules
# COPY . .

# RUN npx prisma generate
# RUN npm run build

# # Stage 3: Production image
# FROM node:20-alpine AS runner
# WORKDIR /app

# ENV NODE_ENV=production

# COPY --from=builder /app/public ./public
# COPY --from=builder /app/.next ./.next
# COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/package.json ./package.json
# COPY --from=builder /app/prisma ./prisma
# COPY --from=builder /app/.env ./.env

# EXPOSE 3000
# CMD ["npm", "start"]
